class OverworldMap {
  constructor(config) {
    this.gameObjects = config.gameObjects;
    this.walls = config.walls || {};
    this.lowerImage = new Image();
    this.lowerImage.src = config.lowerSrc;
  }

  drawLowerImage(ctx, cameraperson) {
    ctx.drawImage(this.lowerImage, utils.withGrid(6)- cameraperson.x, utils.withGrid(4)- cameraperson.y)
  }

  isSpaceTaken(currentX, currentY, direction) {
    const {x,y} = utils.nextPosition(currentX, currentY, direction);
    console.log([`${x},${y}`])
    return this.walls[`${x},${y}`] || false;
  }

  mountObjects() {
    Object.values(this.gameObjects).forEach(o => {

      //TODO: determine if this object should actually mount
      o.mount(this);

    })
  }

  addWall(x,y) {
    this.walls[`${x},${y}`] = true;
  }
  removeWall(x,y) {
    delete this.walls[`${x},${y}`]
  }
  moveWall(wasX, wasY, direction) {
    this.removeWall(wasX, wasY);
    const {x,y} = utils.nextPosition(wasX, wasY, direction);
    this.addWall(x,y);
  }
}

window.OverworldMaps = {
  ///game objects

first_map: {
  lowerSrc: "/images/dridi.png",
  upperSrc: "/images/dridi.png",
  gameObjects: {
    hero: new Person({
      isPlayerControlled: true,
      x: utils.withGrid(2),
      y: utils.withGrid(2),
      src: "/images/warrior_m.png"
    }),
    gobling: new Person({
      x: utils.withGrid(3),
      y: utils.withGrid(3),
      src: "/images/goblin.png"
    }),
    leaf: new Person({
      x: utils.withGrid(5),
      y: utils.withGrid(2),
      src: "/images/leaf.png"
    }),
  },
walls: {
  [utils.asGridCoord(0,0)]: true,
  [utils.asGridCoord(0,1)]: true,
  [utils.asGridCoord(0,2)]: true,
  [utils.asGridCoord(0,3)]: true,
  [utils.asGridCoord(0,4)]: true,
  [utils.asGridCoord(0,5)]: true,
  [utils.asGridCoord(0,6)]: true,
  [utils.asGridCoord(0,7)]: true,
  [utils.asGridCoord(0,8)]: true,
  [utils.asGridCoord(0,9)]: true,
  [utils.asGridCoord(0,10)]: true,
  [utils.asGridCoord(0,11)]: true,
  [utils.asGridCoord(0,12)]: true,
  [utils.asGridCoord(0,13)]: true,
  [utils.asGridCoord(0,14)]: true,
  [utils.asGridCoord(0,15)]: true,
  [utils.asGridCoord(0,16)]: true,
  [utils.asGridCoord(0,17)]: true,
  [utils.asGridCoord(0,18)]: true,
  [utils.asGridCoord(1,1)]: true,
  [utils.asGridCoord(2,1)]: true,
  [utils.asGridCoord(3,1)]: true,
  [utils.asGridCoord(4,1)]: true,
  [utils.asGridCoord(5,1)]: true,
  [utils.asGridCoord(6,1)]: true,
  [utils.asGridCoord(7,1)]: true,
  [utils.asGridCoord(8,1)]: true,
  [utils.asGridCoord(9,1)]: true,
  [utils.asGridCoord(10,1)]: true,
  [utils.asGridCoord(11,1)]: true,
  [utils.asGridCoord(12,1)]: true,
  [utils.asGridCoord(13,1)]: true,
  [utils.asGridCoord(19,1)]: true,
  [utils.asGridCoord(20,1)]: true,
  [utils.asGridCoord(21,1)]: true,
  [utils.asGridCoord(22,1)]: true,
  [utils.asGridCoord(23,1)]: true,
  [utils.asGridCoord(23,0)]: true,
  [utils.asGridCoord(14,0)]: true,
  [utils.asGridCoord(15,0)]: true,
  [utils.asGridCoord(16,0)]: true,
  [utils.asGridCoord(17,0)]: true,
  [utils.asGridCoord(18,1)]: true,
  [utils.asGridCoord(19,1)]: true,
  [utils.asGridCoord(14,0)]: true,
  [utils.asGridCoord(14,1)]: true,
  [utils.asGridCoord(14,2)]: true,
  [utils.asGridCoord(14,3)]: true,
  [utils.asGridCoord(14,4)]: true,
  [utils.asGridCoord(14,5)]: true,
  [utils.asGridCoord(13,5)]: true,
  [utils.asGridCoord(13,6)]: true,
  [utils.asGridCoord(13,7)]: true,
  [utils.asGridCoord(1,6)]: true,
  [utils.asGridCoord(2,6)]: true,
  [utils.asGridCoord(3,6)]: true,
  [utils.asGridCoord(4,6)]: true,
  [utils.asGridCoord(5,6)]: true,
  [utils.asGridCoord(6,6)]: true,
  [utils.asGridCoord(7,6)]: true,
  [utils.asGridCoord(8,6)]: true,
  [utils.asGridCoord(9,6)]: true,
  [utils.asGridCoord(10,6)]: true,
  [utils.asGridCoord(7,5)]: true,
  [utils.asGridCoord(13,6)]: true,
  [utils.asGridCoord(14,6)]: true,
  [utils.asGridCoord(15,6)]: true,
  [utils.asGridCoord(16,6)]: true,
  [utils.asGridCoord(17,6)]: true,
  [utils.asGridCoord(18,6)]: true,
  [utils.asGridCoord(19,6)]: true,
  [utils.asGridCoord(20,6)]: true,
  [utils.asGridCoord(1,7)]: true,
  [utils.asGridCoord(2,7)]: true,
  [utils.asGridCoord(3,7)]: true,
  [utils.asGridCoord(4,7)]: true,
  [utils.asGridCoord(5,7)]: true,
  [utils.asGridCoord(6,7)]: true,
  [utils.asGridCoord(7,7)]: true,
  [utils.asGridCoord(8,7)]: true,
  [utils.asGridCoord(9,7)]: true,
  [utils.asGridCoord(10,7)]: true,
  [utils.asGridCoord(13,7)]: true,
  [utils.asGridCoord(14,7)]: true,
  [utils.asGridCoord(15,7)]: true,
  [utils.asGridCoord(16,7)]: true,
  [utils.asGridCoord(17,7)]: true,
  [utils.asGridCoord(18,7)]: true,
  [utils.asGridCoord(19,7)]: true,
  [utils.asGridCoord(20,7)]: true,
  [utils.asGridCoord(20,3)]: true,
  [utils.asGridCoord(20,4)]: true,
  [utils.asGridCoord(20,5)]: true,
  [utils.asGridCoord(1,11)]: true,
  [utils.asGridCoord(2,11)]: true,
  [utils.asGridCoord(3,11)]: true,
  [utils.asGridCoord(4,11)]: true,
  [utils.asGridCoord(5,11)]: true,
  [utils.asGridCoord(1,12)]: true,
  [utils.asGridCoord(2,12)]: true,
  [utils.asGridCoord(3,12)]: true,
  [utils.asGridCoord(4,12)]: true,
  [utils.asGridCoord(5,11)]: true,
  [utils.asGridCoord(10,7)]: true,
  [utils.asGridCoord(10,8)]: true,
  [utils.asGridCoord(10,9)]: true,
  [utils.asGridCoord(10,10)]: true,
  [utils.asGridCoord(10,11)]: true,
  [utils.asGridCoord(10,12)]: true,
  [utils.asGridCoord(10,13)]: true,
  [utils.asGridCoord(10,14)]: true,
  [utils.asGridCoord(10,15)]: true,
  [utils.asGridCoord(10,16)]: true,
  [utils.asGridCoord(10,17)]: true,
  [utils.asGridCoord(10,18)]: true,
  [utils.asGridCoord(10,19)]: true,
  [utils.asGridCoord(7,3)]: true,
  [utils.asGridCoord(11,18)]: true,
  [utils.asGridCoord(12,18)]: true,
  [utils.asGridCoord(13,18)]: true,
  [utils.asGridCoord(14,18)]: true,
  [utils.asGridCoord(15,18)]: true,
  [utils.asGridCoord(16,18)]: true,
  [utils.asGridCoord(17,18)]: true,
  [utils.asGridCoord(18,18)]: true,
  [utils.asGridCoord(19,18)]: true,
  [utils.asGridCoord(20,18)]: true,
  [utils.asGridCoord(21,18)]: true,
  [utils.asGridCoord(22,18)]: true,
  [utils.asGridCoord(23,18)]: true,
  [utils.asGridCoord(10,12)]: true,
  [utils.asGridCoord(11,12)]: true,
  [utils.asGridCoord(12,12)]: true,
  [utils.asGridCoord(13,12)]: true,
  [utils.asGridCoord(14,12)]: true,
  [utils.asGridCoord(15,12)]: true,
  [utils.asGridCoord(16,12)]: true,
  [utils.asGridCoord(17,12)]: true,
  [utils.asGridCoord(18,12)]: true,
  [utils.asGridCoord(19,12)]: true,
  [utils.asGridCoord(20,12)]: true,
  [utils.asGridCoord(14,11)]: true,
  [utils.asGridCoord(15,11)]: true,
  [utils.asGridCoord(16,11)]: true,
  [utils.asGridCoord(17,11)]: true,
  [utils.asGridCoord(18,11)]: true,
  [utils.asGridCoord(19,11)]: true,
  [utils.asGridCoord(14,9)]: true,
  [utils.asGridCoord(15,9)]: true,
  [utils.asGridCoord(16,9)]: true,
  [utils.asGridCoord(17,9)]: true,
  [utils.asGridCoord(18,9)]: true,
  [utils.asGridCoord(19,9)]: true,
  [utils.asGridCoord(14,8)]: true,
  [utils.asGridCoord(10,13)]: true,
  [utils.asGridCoord(11,13)]: true,
  [utils.asGridCoord(12,13)]: true,
  [utils.asGridCoord(13,13)]: true,
  [utils.asGridCoord(14,13)]: true,
  [utils.asGridCoord(15,13)]: true,
  [utils.asGridCoord(16,13)]: true,
  [utils.asGridCoord(17,13)]: true,
  [utils.asGridCoord(18,13)]: true,
  [utils.asGridCoord(19,13)]: true,
  [utils.asGridCoord(20,13)]: true,
  [utils.asGridCoord(20,14)]: true,
  [utils.asGridCoord(20,15)]: true,
  [utils.asGridCoord(22,15)]: true,
  [utils.asGridCoord(23,15)]: true,
  [utils.asGridCoord(23,0)]: true,
  [utils.asGridCoord(23,1)]: true,
  [utils.asGridCoord(23,2)]: true,
  [utils.asGridCoord(23,3)]: true,
  [utils.asGridCoord(23,4)]: true,
  [utils.asGridCoord(23,5)]: true,
  [utils.asGridCoord(23,6)]: true,
  [utils.asGridCoord(23,7)]: true,
  [utils.asGridCoord(23,8)]: true,
  [utils.asGridCoord(23,9)]: true,
  [utils.asGridCoord(23,10)]: true,
  [utils.asGridCoord(23,11)]: true,
  [utils.asGridCoord(23,12)]: true,
  [utils.asGridCoord(23,13)]: true,
  [utils.asGridCoord(23,14)]: true,
  [utils.asGridCoord(23,15)]: true,
  [utils.asGridCoord(23,16)]: true,
  [utils.asGridCoord(23,17)]: true,
  [utils.asGridCoord(23,18)]: true,
  [utils.asGridCoord(23,19)]: true,
  [utils.asGridCoord(0,19)]: true,
  [utils.asGridCoord(1,19)]: true,
  [utils.asGridCoord(2,19)]: true,
  [utils.asGridCoord(3,19)]: true,
  [utils.asGridCoord(4,19)]: true,
  [utils.asGridCoord(5,19)]: true,
  [utils.asGridCoord(6,19)]: true,
  [utils.asGridCoord(7,19)]: true,
  [utils.asGridCoord(8,19)]: true,
  [utils.asGridCoord(9,19)]: true,
  [utils.asGridCoord(10,19)]: true,
  [utils.asGridCoord(11,19)]: true,
  [utils.asGridCoord(12,19)]: true,
  [utils.asGridCoord(13,19)]: true,
  [utils.asGridCoord(14,19)]: true,
  [utils.asGridCoord(15,19)]: true,
  [utils.asGridCoord(16,19)]: true,
  [utils.asGridCoord(17,19)]: true,
  [utils.asGridCoord(18,19)]: true,
  [utils.asGridCoord(19,19)]: true,
  [utils.asGridCoord(20,19)]: true,
  [utils.asGridCoord(21,19)]: true,
  [utils.asGridCoord(22,19)]: true,
  [utils.asGridCoord(23,19)]: true,
  [utils.asGridCoord(24,19)]: true,
  [utils.asGridCoord(25,19)]: true,
  [utils.asGridCoord(26,19)]: true,
  [utils.asGridCoord(27,19)]: true,
  [utils.asGridCoord(28,19)]: true,
  [utils.asGridCoord(29,19)]: true,
  [utils.asGridCoord(19,5)]: true,
  [utils.asGridCoord(15,5)]: true,
  [utils.asGridCoord(8,2)]: true,
  [utils.asGridCoord(6,3)]: true,
  [utils.asGridCoord(14,8)]: true,
  [utils.asGridCoord(4,8)]: true,
  [utils.asGridCoord(4,9)]: true,
  [utils.asGridCoord(13,14)]: true,
  [utils.asGridCoord(13,17)]: true,
  [utils.asGridCoord(29,0)]: true,
  [utils.asGridCoord(29,1)]: true,
  [utils.asGridCoord(29,2)]: true,
  [utils.asGridCoord(29,3)]: true,
  [utils.asGridCoord(29,4)]: true,
  [utils.asGridCoord(29,5)]: true,
  [utils.asGridCoord(29,6)]: true,
  [utils.asGridCoord(29,7)]: true,
  [utils.asGridCoord(29,8)]: true,
  [utils.asGridCoord(29,9)]: true,
  [utils.asGridCoord(29,10)]: true,
  [utils.asGridCoord(29,11)]: true,
  [utils.asGridCoord(29,12)]: true,
  [utils.asGridCoord(29,13)]: true,
  [utils.asGridCoord(29,14)]: true,
  [utils.asGridCoord(29,15)]: true,
  [utils.asGridCoord(29,16)]: true,
  [utils.asGridCoord(29,17)]: true,
  [utils.asGridCoord(29,18)]: true,
  [utils.asGridCoord(29,19)]: true
}},/////first_map ending

}